language: node.js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  #build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed surdya/udagram-api-feed
  - docker tag udagram-api-user surdya/udagram-api-user
  - docker tag udagram-frontend surdya/udagram-frontend:v1
  - docker tag reverseproxy surdya/reverseproxy
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push surdya/udagram-api-feed
  - docker push surdya/udagram-api-user
  - docker push surdya/udagram-frontend:v1
  - docker push surdya/reverseproxy